### ISSUE TITLE
PyPI release?

### ISSUE THREAD

**Issue by jayvdb** [sio/cirrus-run#1]
Would you be able to do a release on PyPI.

That makes it easier for building distro packages.

**Comment by sio** [comment]
Cirrus-run is now on PyPI: https://pypi.org/project/cirrus-run/

What distro are you planning to package it for?

**Comment by jayvdb** [comment]
Thanks

https://build.opensuse.org/package/show/home:jayvdb:py-new/python-cirrus-run

**Comment by sio** [comment]
Cool! 👍
