### ISSUE TITLE
Is security breach possible?

### ISSUE THREAD

**Issue by sio** [sio/cirrus-run#2]
I'd like to gather some opinions on whether a security breach is possible when using cirrus-run.

The scenario I have in mind is like this:

- Some third-party CI service, e.g. GitLab, is used to execute cirrus-run
- Sensitive information is provided via environment variables, e.g. `CIRRUS_API_TOKEN`
- Jinja2 templating is used to configure Cirrus CI build (`.cirrus.yml.j2`)

Can a malicious actor with read-only access to the third-party service (GitLab) cause a leak of sensitive information?

I think no. At least when sensitive information is stored according to best practices (masked in GitLab). Malicious actor would likely try to create a custom `.cirrus.yml.j2` to expose the value of environment variable - and then would try to trigger a CI run via pull request. In that case PR would be executed from actor's repo and masked values would not be propagated from upstream.

Am I right? Is there some attack vector I overlooked?

**Comment by berrange** [comment]
I think the key risk is that a sensitive variable can end up being "echoed" during the build process, such that its value ends up recorded in the log file. The log files in public CI systems are typically accessible to any anonymous internet user.

So there is definitely a risk to CIRRUS_API_TOKEN, if anything were to (accidentally) echo its value during a build.

To address this GitLab CI allows you to mark environment variables as "masked". When you do this, GitLab will search for any occurrances of the variable value in the logs and scrub them. So CIRRUS_API_TOKEN must always be set as "masked" if used from GitLab CI. Similar precautions would apply to any other CI system using cirus-run.

In terms of the cirrus.yml.j2 template, I think the scrubbing would probably protect that if its contents were echoed & contained the API token, but obviously it is wise to avoid echoing the expanded contents at all just to be sure.

**Comment by sio** [comment]
Yeah, unintentional echoing is a possibility, but am I right that only project members with write access can introduce that? In my opinion that would fall under the "best practices" umbrella - if you want to shoot yourself in the foot there is not much cirrus-run can do to stop you.

If `.cirrus.yml.j2` is not already echoing sensitive data outside actors can not change that, correct?

**Comment by berrange** [comment]
Yeah, 3rd parties should be limited to merely whatever is in the log file and can't influence what runs, untill after a maintainer has approved merge into the main repo.

Note that when a user forks a repo, any testing happens in the context of their private fork, not the original repo, so has no access to any env variables. The user has to configure their own CIRRUS_API_TOKEN in their private fork.

**Comment by sio** [comment]
Thank you for confirming my deductions!
