### ISSUE TITLE
Show full CI log on stdout

### ISSUE THREAD

**Issue by sio** [sio/cirrus-run#3]
It would be more informative to provide full CI log on stdout instead of just dots progress indicator. This has also been requested by libvirt team: https://www.redhat.com/archives/libvir-list/2020-June/msg00253.html

If fetching the log in real time is too difficult, dots should stay but full log may be shown afterwards for failed builds.

Fixing this would require composing a GraphQL query that returns build log after being given a build id (or task id).

**Comment by andreabolognani** [comment]
Thanks for tracking this!

Just a minor clarification:

> If fetching the log in real time is too difficult, dots should stay but full log may be shown afterwards for failed builds.

I think it would be great if the full log would be shown unconditionally, regardless of whether the Cirrus CI job has failed or succeeded. It's perfectly if this behavior is locked behind a command line option, of course.

**Comment by sio** [comment]
Comment from Daniel P. Berrangé on [libvir-list](https://www.redhat.com/archives/libvir-list/2020-July/msg01981.html):

> 
> FWIW, I don't think we need to have "live" logs while the job is
> running. That's more of a nice to have category.
> 
> What I was mostly interested in was to simply pull over the log
> output once the job completes/fails. Essentially so that when
> someone goes to browse the job results upon completion of the
> GitLab pipeline, all the log data is viewable from the same
> place. This would also mean that the GitLab emails sent on
> failure would be able to include the last 20 lines of the
> real build failure.
> 
> So possibly that is as simple as just figuring out the URL where
> Cirrus CI stores the log and just pulling down its contents. May
> not really involve the Cirrus CI API at all. In fact we could
> probably do that in libvirt's GitLab CI rules, but if cirrus-run
> wants to provide this kind of feature it'd obviously make it more
> accessible to a wider userbase.
>

**Comment by sio** [comment]
I have merged the described feature to master. 

I will test for a few days with my CI pipelines and will make a new PyPI release after.
